### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Sarouch** [giovannicimolin/PascalVOC-to-Images#3]
Hello,
I tried to figure out this error :

 Traceback (most recent call last):
  File "main.py", line 80, in <module>
    process()
  File "main.py", line 35, in process
    extractDataset(index['annotation'])
  File "main.py", line 72, in extractDataset
    im.save(sample_preamble + str(i) + '.jpg')
  File "C:\Users\c\anaconda3\envs\py38\lib\site-packages\PIL\Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '154_10001/154_10001_0.jpg'

I only have 2 folders generated from image 1 and 10 then the error appear ! where are images 2,3,4... please did you have this issue before ?  I miss something ?

**Comment by giovannicimolin** [comment]
@Sarouch Hi! Sorry, I had notifications disabled and didn't notice your ping.
Let me know if you are still using this, I can clean up the repository a bit.
I also accept contributions if you have some fixes!
